version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - add_ssh_keys:
          fingerprints:
            - "19:f9:c7:4d:97:32:ee:96:84:d2:20:df:10:71:72:7f"
       - run: npm install
       - run: npm run format
       - run: npm run build
       - run: cp package.json build/
       - run: node deploy_app.js
       - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts
       - run: ssh $SSH_USER@$SSH_HOST "cd domains/pogoda.wroblewskipiotr.pl/public_html/ && devil www restart pogoda.wroblewskipiotr.pl"


workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master