version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - add_ssh_keys:
          fingerprints:
            - "67:3a:22:2c:f1:74:2c:ae:64:7b:5f:93:69:eb:1e:fb"
       - run: npm install
       - run: npm run format
       - run: npm run build
       - run: cp package.json build/
       - run: node deploy_app.js
       - run: ssh-keyscan -H 's21.mydevil.net' >> ~/.ssh/known_hosts
       - run: ssh $SSH_USER@$SSH_HOST "cd domains/pogoda.wroblewskipiotr.pl/public_html/ && devil www restart pogoda.wroblewskipiotr.pl"


workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master