version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: npm install
       - run: npm run format
       - run: npm run build
       - run: git log --oneline --decorate > public/changelog.txt
       - run: node deploy_app.js

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
               - master